server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: En@ck2022
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:

    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
